name: Verificação de senha

on: [push]

jobs:
  branch1:
    runs-on: ubuntu-latest

    steps:
    - name: Checar senha - Branch 1
      run: python verificar_senha.py

  branch2:
    runs-on: ubuntu-latest

    steps:
    - name: Checar senha - Branch 2
      run: pytest teste_verificar_senha.py
